# Generated by Django 3.2.25 on 2026-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_detallepedido_producto_remove_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('SUPERIOR', 'Prenda Superior (Poleras, Polerones, Blusas)'), ('INFERIOR', 'Prenda Inferior (Pantalones, Faldas, Shorts)'), ('CALZADO', 'Zapatillas, Zapatos'), ('ACCESORIO', 'Gorros, Bolsos, Lentes')], default='SUPERIOR', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='color_base',
            field=models.CharField(blank=True, help_text='Ej: Negro, Blanco, Rojo', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre'), ('U', 'Unisex')], default='U', max_length=1),
        ),
    ]
