# Generated by Django 3.2.25 on 2026-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20260820_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('M', 'Mujer'), ('U', 'Unisex')], default='U', max_length=1),
        ),
    ]
