# Generated by Django 3.2.25 on 2026-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AddField(
            model_name='producto',
            name='estilo',
            field=models.CharField(choices=[('CASUAL', 'Casual / Diario'), ('FORMAL', 'Formal / Oficina'), ('FIESTA', 'Noche / Fiesta'), ('SPORT', 'Deportivo / Comodidad')], default='CASUAL', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='temporada',
            field=models.CharField(choices=[('VERANO', 'Primavera / Verano'), ('INVIERNO', 'Otoño / Invierno'), ('ATEMPORAL', 'Atemporal (Todo el año)')], default='ATEMPORAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('SUPERIOR', 'Prenda Superior (Poleras, Blusas)'), ('INFERIOR', 'Prenda Inferior (Pantalones, Faldas)'), ('CALZADO', 'Zapatillas, Zapatos'), ('ACCESORIO', 'Gorros, Bolsos, Lentes')], default='SUPERIOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_base',
            field=models.CharField(choices=[('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('JEANS', 'Denim / Jeans'), ('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('BEIGE', 'Beige/Café'), ('OTRO', 'Otro / Estampado')], default='NEGRO', max_length=15),
        ),
    ]
