# Generated by Django 3.2.25 on 2026-08-22 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tienda.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20260820_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(default=tienda.models.generar_codigo_seguimiento, editable=False, max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_despacho',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mecanismo_seguimiento',
            field=models.CharField(default='Consulta con tu RUT y código de seguimiento en LogisFlow.', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plazo_entrega',
            field=models.CharField(default='No informado', max_length=150),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('SUPERIOR', 'Tops y poleras (general)'), ('POLERAS', 'Poleras y tops'), ('BLUSAS', 'Blusas'), ('INFERIOR', 'Pantalones y faldas (general)'), ('PANTALONES', 'Pantalones y jeans'), ('FALDAS', 'Faldas'), ('VESTIDOS', 'Vestidos'), ('CHAQUETAS', 'Chaquetas y abrigos'), ('CALZADO', 'Calzado'), ('ACCESORIO', 'Accesorios')], default='SUPERIOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_base',
            field=models.CharField(choices=[('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('BEIGE', 'Beige / Café'), ('JEANS', 'Denim / Jeans'), ('ROSADO', 'Rosado'), ('FUCSIA', 'Fucsia'), ('LILA', 'Lila'), ('MORADO', 'Morado'), ('CORAL', 'Coral'), ('BURDEO', 'Burdeo'), ('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('OTRO', 'Otro / Estampado')], default='NEGRO', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_entrega', models.CharField(max_length=50)),
                ('items', models.JSONField()),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal_productos', models.PositiveIntegerField(default=0)),
                ('costo_despacho', models.PositiveIntegerField(default=0)),
                ('plazo_entrega', models.CharField(default='No informado', max_length=150)),
                ('mecanismo_seguimiento', models.CharField(default='Consulta con tu RUT y código de seguimiento en LogisFlow.', max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('CONFIRMADO', 'Pago confirmado'), ('SIN_STOCK', 'No se pudo asignar stock'), ('EXPIRADO', 'Reserva expirada'), ('CANCELADO', 'Pago cancelado')], default='PENDIENTE', max_length=20)),
                ('reserva_activa', models.BooleanField(default=False)),
                ('reserva_expira_en', models.DateTimeField(blank=True, null=True)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='tienda.pedido')),
            ],
        ),
    ]
