# Generated by Django 3.2.25 on 2026-08-22 23:40

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_codigo_seguimiento_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(default=tienda.models.generar_codigo_seguimiento, editable=False, max_length=13, unique=True),
        ),
    ]
