# Generated by Django 3.2.25 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_privacidad_cuentas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pagopendiente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
