# Generated by Django 3.2.25 on 2026-08-23

from django.db import migrations, models


def limpiar_telefonos_vacios(apps, schema_editor):
    Cliente = apps.get_model('tienda', 'Cliente')
    Cliente.objects.filter(telefono='').update(telefono=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_cliente_y_pago_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(limpiar_telefonos_vacios, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
