# Generated by Django 6.1 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_cliente_telefono_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
